- hosts: server
  roles:
    - install_docker

  tasks:

    - name: "Create Certificates directory for Docker"
      file:
        path: /dockertls/
        state: directory

    - name: "Copy Private Key to Server"
      copy:
        src: certificates/server/server-privatekey.pem
        dest: /dockertls/server-privatekey.pem

    - name: "Copy Certificate to Server"
      copy:
        src: certificates/server/server-certificate.pem
        dest: /dockertls/server-certificate.pem

    - name: "Copy RootCA to Server (For client verification)"
      copy:
        src: certificates/rootca-certificate.pem
        dest: /dockertls/rootca-certificate.pem

    - name: "Create Overrides directory for Docker"
      file:
        path: /etc/systemd/system/docker.service.d/
        state: directory

    - name: "Push the Docker daemon config to Server"
      copy:
        src: daemon_startup_options.conf
        dest: /etc/systemd/system/docker.service.d/daemon_startup_options.conf

    - name: "Restart Docker Daemon service"
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes
