- name: "Install requirements"
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  become: yes

- name: "Add docker GPG key"
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: "Add docker repo"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu  {{ ansible_lsb.codename }}  stable"
    state: present
  become: yes

- name: "Install Docker"
  apt:
    name: docker-ce
    update_cache: yes
    state: latest
  become: yes
