- hosts: sandbox

  vars:
    certdir: "/home/shockn745/config-in-the-cloud/secrets/tlscertificates-awesometeam"

  tasks:
    - include_role:
        name: FlorianKempenich.setup-secure-remote-docker-daemon
      vars:
        rootca_certificate: "{{ lookup('file', '{{ certdir }}/rootca-certificate.pem') }}"
        server_certificate: "{{ lookup('file', '{{ certdir }}/server/server-certificate.pem') }}"
        server_privatekey: "{{ lookup('file',  '{{ certdir }}/server/server-privatekey.pem') }}"


