- hosts: all

  tasks:
    - name: "Install requirements"
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      become: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: "Add docker GPG key"
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Add docker repo"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu  {{ ansible_lsb.codename }}  stable"
        state: present

    - name: "Install Docker"
      apt:
        name: docker-ce
        update_cache: yes
        state: latest
      become: yes

    - name: "Check installation"
      shell: docker run hello-world
      become: yes

    - name: "Disable Docker Daemon"
      systemd:
        name: docker
        state: stopped
        enabled: no
